//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMember
    {
        public int Id { get; set; }
        public string TeamID { get; set; }
        public string PlayerName { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Team Team { get; set; }
    }
}
