//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TournamentEntities : DbContext
    {
        public TournamentEntities()
            : base("name=TournamentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Matchup> Matchup { get; set; }
        public virtual DbSet<MatchupEntries> MatchupEntries { get; set; }
        public virtual DbSet<People> People { get; set; }
        public virtual DbSet<TeamMembers> TeamMembers { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
        public virtual DbSet<TournamentEntries> TournamentEntries { get; set; }
        public virtual DbSet<Tournaments> Tournaments { get; set; }
    }
}
